name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy the site to Github Pages.
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
